    # page.get_by_text("Users & Roles").click()
    # page.get_by_role("link", name="User List").click()
    # page.get_by_role("link", name="Bulk User Create").click()
    # page.get_by_label("Document(Only .xls, .xlsx) *").click()
    # page.get_by_label("Document(Only .xls, .xlsx) *").set_input_files("upgradesim.py")
    # page.get_by_role("button", name="Upload").click()
    # page.get_by_text("Uploaded Successfully...").click()
    # page.get_by_role("link", name="Bulk User Create").click()
    # page.get_by_label("Document(Only .xls, .xlsx) *").click()
    # page.get_by_text("Document need to be uploaded").click()
    # page.get_by_label("Document(Only .xls, .xlsx) *").click()
    # page.get_by_label("Document(Only .xls, .xlsx) *").set_input_files("upgradesim.py")
    # page.locator("form div").filter(has_text="Upload").nth(1).click()
    # page.get_by_text("Uploaded Successfully...").click()